#默认使用配置
spring:
  elasticsearch:
    jest:
      uris: http://localhost:9200
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  profiles:
    active: dev
  datasource:
    url: jdbc:sqlserver://PC201401120046:1433;DatabaseName=XrLearn
    username: xiaoran1
    password: 2222
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    open-in-view: false

  #公共配置与profiles选择无关
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.hxr.springbootdemo.entity
    config-location: classpath:mybatis-config.xml

server:
  #端口号
  port: 8888


