#默认使用配置
spring:
  elasticsearch:
    jest:
      uris: http://localhost:9200
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  profiles:
    active: dev
  datasource:
    url: jdbc:sqlserver://PC201401120046:1433;DatabaseName=XrLearn
    username: xiaoran1
    password: 2222
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  #公共配置与profiles选择无关
mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    type-aliases-package: com.hxr.springbootdemo.entity

server:
  #端口号
  port: 8888


